apiVersion: 1

datasources:
  - name: PostgreSQL-AppDB
    orgId: 1
    type: postgres
    access: proxy
    url: multitenant-postgres:5432
    database: appdb
    user: appuser
    secureJsonData:
      password: apppassword
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1600
    isDefault: true
    editable: true

